### ISSUE TITLE
命令ブロックからルビーに変換するときの挙動

### ISSUE THREAD

**Issue by fujimurakengo** [smalruby/smalruby3-gui#192]
### Expected Behavior

https://scratch.mit.edu/projects/291938553/

https://smalruby.jp/smalruby3-gui/#291938553

このプロジェクトを例にとって考える

本来なら指定のリストの場所を指定したとき
    ask(list("$県名")[$乱数] + "が県庁所在地の県はどこかな")

となるはず

### Actual Behavior

実際には
    ask(list("$県名")[0] + "が県庁所在地の県はどこかな")
となっている
$乱数が0を上書きできていない

### Steps to Reproduce
0を変数で上書きできていないだけではないかと思われる
_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

windows 10 72.0.3626.121（Official Build） （64 ビット）
_e.g. Mac OS 10.11.6 Safari 10.0_

ルビーで間違いを正しても再度ルビーの画面に変更すると
    ask(list("$県名")[0] + "が県庁所在地の県はどこかな")
となる
挙動そのものにおかしなところはないです．

**Comment by takaokouji** [comment]
最新のコードだときちんと$乱数になった。closeする。
