### ISSUE TITLE
Could not convert extension ruby code to block if never enabled that extension.

### ISSUE THREAD

**Issue by fujimurakengo** [smalruby/smalruby3-gui#217]
### Expected Behavior

スモウルビー３を起動したあと，ルビーで拡張機能に存在するプログラムを書いて
ブロックに変換すると変換できる

### Actual Behavior

スモウルビー３を起動したあと，ルビーで拡張機能に存在するプログラムを書いて
ブロックに変換すると変換できず赤いブロックになる

### Steps to Reproduce

１スモウルビー３を新しいタブで起動する
２
microbit.display_text("Hello!")
とルビーでかく
３変換されない

### Operating System and Browser

win10 Chrome

**Comment by takaokouji** [comment]
<img width="398" alt="スクリーンショット 2020-02-24 13 59 24" src="https://user-images.githubusercontent.com/52317/75129764-f4b64a00-570d-11ea-8b2a-059f0f5f7039.png">

を入力して、コードタブに切り替えると次のようになる。

<img width="287" alt="スクリーンショット 2020-02-24 13 59 34" src="https://user-images.githubusercontent.com/52317/75129765-f5e77700-570d-11ea-9211-03fcbb0748f7.png">
