### ISSUE TITLE
ローカライズに伴う文言問題

### ISSUE THREAD

**Issue by t-kazu** [smalruby/smalruby3-gui#23]
#21 のマージでタイトルにCatが入ってしまっています。
また、ローカライズの関係かもしれませんが、トップモーダルで『Scratch 3.0プレビュー版にようこそ』と出ています。

**Comment by t-kazu** [comment]
https://github.com/LLK/scratch-l10n　こちらのリポジトリが影響しているみたいです。
node_modulesの中にあるファイルが影響しているみたいです。

解決するには、scratch-10nをfork smalruby-10n を作成しそちらを`npm install`するパターン。もしくは必要なところだけ独自のtranslationファイルを作成するの２通りが考えられます。
ローカライズは、Scratch本家がreact-intlを使っています。https://github.com/yahoo/react-intl ローカライズの中ではトップ２に入るほど有名なパッケージですね。

**Comment by t-kazu** [comment]
Smalruby独自のローカライズid一覧
`gui.smalruby3.unsupportedBrowser.description`
`gui.smalruby3.previewInfo.welcome`
`gui.smalruby3.previewInfo.invitation`
`gui.smalruby3.webglModal.description`
`gui.smalruby3.previewInfo.label`
`gui.smalruby3.gui.rubyTab`
`gui.smalruby3.previewInfo.betawelcome`

以下、３つはプレビューモーダルで表示される内容のため、必要ありません。
`gui.smalruby3.previewInfo.betawelcome`
`gui.smalruby3.previewInfo.invitation`
`gui.smalruby3.previewInfo.welcome`

**Comment by takaokouji** [comment]
@t-kazu 
#26 でこのissueで想定していた作業は完了ですかね？もしそうならば、このissueはcloseします。

**Comment by t-kazu** [comment]
そうですね。issue的には終わりなのでこちらをClosedして新しいissueを作る流れでしょうか？
メッセージカタログの追加　みたいな

**Comment by takaokouji** [comment]
@t-kazu
提案してもらった通り、

> issue的には終わりなのでこちらをClosedして新しいissueを作る流れでしょうか？
> メッセージカタログの追加　みたいな

をお願いします。
