### ISSUE TITLE
検索機能の追加

### ISSUE THREAD

**Issue by takaokouji** [smalruby/smalruby3-gui#267]
Ctrl+FとかCommand+Fとかで検索できるようにする。メニューから検索を選んだときでもいい。

https://ace.c9.io/ のエディタで Ctrl+F や command+F でどのような機能を想定しているのかを確認できる。

**Comment by matsudai** [comment]
StackOverflowの記事が参考になりそうでした。

```js
import 'brace';
import 'brace/ext/searchbox';
```

を追加すると良いとのことだったので `src\containers\ruby-tab.jsx` に `brace/ext/searchbox` をインポートすると良さそうです。

https://stackoverflow.com/questions/45724987/how-to-include-ext-searchbox-js-in-my-javascript-bundle
