### ISSUE TITLE
Ruby->コード/LEGO Education WeDo 3.0

### ISSUE THREAD

**Issue by matsudai** [smalruby/smalruby3-gui#284]

**Comment by riversunlight** [comment]
WeDo3.0って拡張機能のところにありませんが、WeDo2.0のことでしょうか
?

**Comment by riversunlight** [comment]
もし、WeDo2.0があれば#301で完成しています。
確認よろしくお願いします。
(CIのほうでnpm が動かないといわれていますが、他は大丈夫だともいます)

**Comment by matsudai** [comment]
@riversunlight すみません、WeDo2.0です。（LEGO MINDSTORM EV3と混ざってました）

> WeDo3.0って拡張機能のところにありませんが、WeDo2.0のことでしょうか

#301 でのご対応ありがとうございます！

このIssueはクローズいたします。
