### ISSUE TITLE
統合テストでエラーが出る

### ISSUE THREAD

**Issue by t-kazu** [smalruby/smalruby3-gui#29]
以下のコマンドを実行するとエラーが確認できるので、解消する
```
$ test:integration
```

**Comment by takaokouji** [comment]
@t-kazu 
これは完了ってことでいいのかな？

**Comment by t-kazu** [comment]
まだ解消できていないです

**Comment by takaokouji** [comment]
手元で試したときのログを追加します。

[test_integration.log](https://github.com/smalruby/smalruby3-gui/files/2496205/test_integration.log)
[2018-10-19T14_22_11_305Z-debug.log](https://github.com/smalruby/smalruby3-gui/files/2496211/2018-10-19T14_22_11_305Z-debug.log)
