### ISSUE TITLE
Define block with same arguments can't convert block to ruby.

### ISSUE THREAD

**Issue by laminne** [smalruby/smalruby3-gui#303]
Japanese description.

ブロック定義で同じ型の引数を2つ以上持つものを作るとルビーへの変換に失敗する

### Actual Behavior

画像のようにブロック定義で同じ型の引数を(e.g.: 真偽値と真偽値、数値と数値)2つ以上持つものを作るとルビーからコードへの変換に失敗する  
(自動生成される変数名が被ることが原因？)

![image](https://user-images.githubusercontent.com/40442980/170455074-d5047ea4-489f-4ae6-92a0-8f46aa539c45.png)

### Operating System and Browser

Windows 10 x86_64, Firefox v.100.0.2 (64-bit)

**Comment by takaokouji** [comment]
確認しました。これは仕様ということにします。
