### ISSUE TITLE
Rubyタブのエディタのフォントサイズを調整する

### ISSUE THREAD

**Issue by t-kazu** [smalruby/smalruby3-gui#59]
以下の写真のように、日本語が含まれると文字が被ってしまうことがあります。
![screenshot from 2018-10-16 16-59-52](https://user-images.githubusercontent.com/23467008/47061919-ad14d980-d20e-11e8-980a-0c2d1f11bf4d.png)

フォントサイズ等の調整し、文字が被らないようにします。

**Comment by takaokouji** [comment]
@t-kazu フォントの種類は以下で指定できました。

```diff
diff --git a/src/containers/ruby-tab.jsx b/src/containers/ruby-tab.jsx
index 82ad166a..a815c1a6 100644
--- a/src/containers/ruby-tab.jsx
+++ b/src/containers/ruby-tab.jsx
@@ -10,6 +10,9 @@ const RubyTab = ({rubyCode}) => (
         readOnly
         editorProps={{$blockScrolling: true}}
         fontSize={16}
+        style={{
+            "font-family": "monaco"
+        }}
         height="inherit"
         mode="ruby"
         name="ruby-editor"
```

あとは、いい感じのフォントを選択することなのですが、なにも設定していなくてもmacだと問題なく表示できています。このため、Windows or Linuxのときのフォントを調整する必要があります。ようするに、武本さんの手元でいい感じになればOK。

なにがいいかわからないため、以下を参考に設定してみて、よさそうならばコミットしてくださいませ。
https://github.com/contao/core/issues/7103#issuecomment-46229725

```css
    font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
```
